name: build

on:
  push:
    branches:
    tags:
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 5.0.x

    - name: Set manifest version
      run: ./bsipa_version_hash.ps1 "Source\CustomAvatar\manifest.json"

    - name: Fetch Beat Saber Bindings
      uses: actions/checkout@v2
      with:
        repository: nicoco007/BeatSaberBindings
        ref: v${{ env.GAME_VERSION }}
        token: ${{ secrets.PRIVATE_GITHUB_TOKEN }}
        path: BeatSaberBindings\Beat Saber_Data\Managed

    - name: Build Debug
      run: dotnet build Source\CustomAvatar\CustomAvatar.csproj -c Debug -p:BeatSaberDir=..\..\BeatSaberBindings

    - name: Upload Debug
      uses: actions/upload-artifact@v2.2.0
      with:
        name: BeatSaberCustomAvatars-${{ env.ZIP_VERSION }}-DEBUG
        path: Source\CustomAvatar\bin\Debug\net472\publish

    - name: Build Release
      run: dotnet build Source\CustomAvatar\CustomAvatar.csproj -c Release -p:BeatSaberDir=..\..\BeatSaberBindings

    - name: Upload Release
      uses: actions/upload-artifact@v2.2.0
      with:
        name: BeatSaberCustomAvatars-${{ env.ZIP_VERSION }}-RELEASE
        path: Source\CustomAvatar\bin\Release\net472\publish

    - name: Build Editor
      run: dotnet build Source\CustomAvatar-Editor\CustomAvatar-Editor.csproj -c Release -p:BeatSaberDir=..\..\BeatSaberBindings

    - name: Upload Editor
      uses: actions/upload-artifact@v2.2.0
      with:
        name: BeatSaberCustomAvatars-${{ env.ZIP_VERSION }}-Editor
        path: Source\CustomAvatar-Editor\bin\Release\net472\publish\CustomAvatar.dll
    
    - name: Upload Unity Project
      uses: actions/upload-artifact@v2.2.0
      with:
        name: BeatSaberCustomAvatars-${{ env.ZIP_VERSION }}-UnityProject
        path: Unity
